// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);

pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 55248573;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_cst structs

#[repr(C)]
pub struct wire_cst_list_prim_u_8_strict {
    ptr: *mut u8,
    len: i32,
}

#[repr(C)]
pub struct wire_cst_list_String {
    ptr: *mut *mut wire_cst_list_prim_u_8_strict,
    len: i32,
}

#[repr(C)]
pub struct wire_cst_sync_config {
    sync_folder: *mut wire_cst_list_prim_u_8_strict,
    database_path: *mut wire_cst_list_prim_u_8_strict,
    sync_interval_seconds: u32,
    max_upload_speed_kbps: u32,
    max_download_speed_kbps: u32,
    delta_sync_enabled: bool,
    delta_sync_min_size: u64,
    pause_on_metered: bool,
    wifi_only: bool,
    watch_filesystem: bool,
    ignore_patterns: *mut wire_cst_list_String,
    notifications_enabled: bool,
    launch_at_startup: bool,
    minimize_to_tray: bool,
}

// Section: CstDecode implementations

impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
    fn cst_decode(self) -> String {
        let vec: Vec<u8> = self.cst_decode();
        String::from_utf8(vec).unwrap()
    }
}

impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
    fn cst_decode(self) -> Vec<u8> {
        unsafe {
            let wrap = &*self;
            std::slice::from_raw_parts(wrap.ptr, wrap.len as usize).to_vec()
        }
    }
}

impl CstDecode<Vec<String>> for *mut wire_cst_list_String {
    fn cst_decode(self) -> Vec<String> {
        let vec = unsafe { &*self };
        let mut result = Vec::with_capacity(vec.len as usize);
        for i in 0..vec.len {
            unsafe {
                let item = *vec.ptr.add(i as usize);
                result.push(CstDecode::<String>::cst_decode(item));
            }
        }
        result
    }
}

impl CstDecode<crate::domain::entities::SyncConfig> for *mut wire_cst_sync_config {
    fn cst_decode(self) -> crate::domain::entities::SyncConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::domain::entities::SyncConfig>::cst_decode(*wrap)
    }
}

impl CstDecode<crate::domain::entities::SyncConfig> for wire_cst_sync_config {
    fn cst_decode(self) -> crate::domain::entities::SyncConfig {
        crate::domain::entities::SyncConfig {
            sync_folder: self.sync_folder.cst_decode(),
            database_path: self.database_path.cst_decode(),
            sync_interval_seconds: self.sync_interval_seconds,
            max_upload_speed_kbps: self.max_upload_speed_kbps,
            max_download_speed_kbps: self.max_download_speed_kbps,
            delta_sync_enabled: self.delta_sync_enabled,
            delta_sync_min_size: self.delta_sync_min_size,
            pause_on_metered: self.pause_on_metered,
            wifi_only: self.wifi_only,
            watch_filesystem: self.watch_filesystem,
            ignore_patterns: self.ignore_patterns.cst_decode(),
            notifications_enabled: self.notifications_enabled,
            launch_at_startup: self.launch_at_startup,
            minimize_to_tray: self.minimize_to_tray,
        }
    }
}

impl CstDecode<crate::domain::entities::ConflictResolution> for i32 {
    fn cst_decode(self) -> crate::domain::entities::ConflictResolution {
        match self {
            0 => crate::domain::entities::ConflictResolution::KeepLocal,
            1 => crate::domain::entities::ConflictResolution::KeepRemote,
            2 => crate::domain::entities::ConflictResolution::KeepBoth,
            3 => crate::domain::entities::ConflictResolution::Skip,
            _ => unreachable!("Invalid enum value: {}", self),
        }
    }
}

// Section: wire function implementations

fn wire__crate__api__oxicloud__get_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_config().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_conflicts_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_conflicts",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_conflicts().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_pending_items_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_pending_items",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_pending_items().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_remote_folders_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_remote_folders",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_remote_folders().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_server_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_server_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_server_info().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_sync_folders_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_sync_folders",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_sync_folders().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_sync_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    limit: u32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_sync_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_sync_history(limit).await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__get_sync_status_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_sync_status",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::get_sync_status().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__simple__greet_impl(
    name: *mut wire_cst_list_prim_u_8_strict,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_name = name.cst_decode();
            transform_result_dco::<_, String, ()>(Ok(crate::api::simple::greet(api_name)))
        },
    )
}

fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco::<_, (), ()>(Ok(crate::api::simple::init_app()))
            }
        },
    )
}

fn wire__crate__api__oxicloud__initialize_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    config: *mut wire_cst_sync_config,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_config = config.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::initialize(api_config).await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__is_logged_in_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_logged_in",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::is_logged_in().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    server_url: *mut wire_cst_list_prim_u_8_strict,
    username: *mut wire_cst_list_prim_u_8_strict,
    password: *mut wire_cst_list_prim_u_8_strict,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_server_url = server_url.cst_decode();
            let api_username = username.cst_decode();
            let api_password = password.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::login(
                        api_server_url,
                        api_username,
                        api_password,
                    )
                    .await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__logout_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "logout",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::logout().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__resolve_conflict_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    conflict_id: *mut wire_cst_list_prim_u_8_strict,
    resolution: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resolve_conflict",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_conflict_id = conflict_id.cst_decode();
            let api_resolution: crate::domain::entities::ConflictResolution =
                resolution.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::resolve_conflict(
                        api_conflict_id,
                        api_resolution,
                    )
                    .await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__set_sync_folders_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    folder_ids: *mut wire_cst_list_String,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_sync_folders",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_folder_ids = folder_ids.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok =
                        crate::api::oxicloud::set_sync_folders(api_folder_ids).await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__shutdown_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "shutdown",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::shutdown().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__start_sync_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_sync",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::start_sync().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__stop_sync_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_sync",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::stop_sync().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__sync_now_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_now",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::sync_now().await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

fn wire__crate__api__oxicloud__update_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    config: *mut wire_cst_sync_config,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_config = config.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>((move || async move {
                    let output_ok = crate::api::oxicloud::update_config(api_config).await?;
                    Ok(output_ok)
                })()
                .await)
            }
        },
    )
}

// Section: rust2dart — IntoDart implementations

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::AuthResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.success.into_into_dart().into_dart(),
            self.user_id.into_into_dart().into_dart(),
            self.username.into_into_dart().into_dart(),
            self.server_info.into_into_dart().into_dart(),
            self.access_token.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::AuthResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::AuthResult> for crate::api::oxicloud::AuthResult {
    fn into_into_dart(self) -> crate::api::oxicloud::AuthResult { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::ServerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.url.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.webdav_url.into_into_dart().into_dart(),
            self.quota_total.into_into_dart().into_dart(),
            self.quota_used.into_into_dart().into_dart(),
            self.supports_delta_sync.into_into_dart().into_dart(),
            self.supports_chunked_upload.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::ServerInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::ServerInfo> for crate::domain::entities::ServerInfo {
    fn into_into_dart(self) -> crate::domain::entities::ServerInfo { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::SyncConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.sync_folder.into_into_dart().into_dart(),
            self.database_path.into_into_dart().into_dart(),
            self.sync_interval_seconds.into_into_dart().into_dart(),
            self.max_upload_speed_kbps.into_into_dart().into_dart(),
            self.max_download_speed_kbps.into_into_dart().into_dart(),
            self.delta_sync_enabled.into_into_dart().into_dart(),
            self.delta_sync_min_size.into_into_dart().into_dart(),
            self.pause_on_metered.into_into_dart().into_dart(),
            self.wifi_only.into_into_dart().into_dart(),
            self.watch_filesystem.into_into_dart().into_dart(),
            self.ignore_patterns.into_into_dart().into_dart(),
            self.notifications_enabled.into_into_dart().into_dart(),
            self.launch_at_startup.into_into_dart().into_dart(),
            self.minimize_to_tray.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::SyncConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::SyncConfig> for crate::domain::entities::SyncConfig {
    fn into_into_dart(self) -> crate::domain::entities::SyncConfig { self }
}

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::SyncResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.success.into_into_dart().into_dart(),
            self.items_uploaded.into_into_dart().into_dart(),
            self.items_downloaded.into_into_dart().into_dart(),
            self.items_deleted.into_into_dart().into_dart(),
            self.conflicts.into_into_dart().into_dart(),
            self.errors.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::SyncResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::SyncResult> for crate::api::oxicloud::SyncResult {
    fn into_into_dart(self) -> crate::api::oxicloud::SyncResult { self }
}

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::SyncStatusInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.is_syncing.into_into_dart().into_dart(),
            self.current_operation.into_into_dart().into_dart(),
            self.progress_percent.into_into_dart().into_dart(),
            self.items_synced.into_into_dart().into_dart(),
            self.items_total.into_into_dart().into_dart(),
            self.last_sync_time.into_into_dart().into_dart(),
            self.next_sync_time.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::SyncStatusInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::SyncStatusInfo> for crate::api::oxicloud::SyncStatusInfo {
    fn into_into_dart(self) -> crate::api::oxicloud::SyncStatusInfo { self }
}

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::SyncHistoryEntry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
            self.operation.into_into_dart().into_dart(),
            self.item_path.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::SyncHistoryEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::SyncHistoryEntry> for crate::api::oxicloud::SyncHistoryEntry {
    fn into_into_dart(self) -> crate::api::oxicloud::SyncHistoryEntry { self }
}

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::RemoteFolder {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.item_count.into_into_dart().into_dart(),
            self.is_selected.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::RemoteFolder {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::RemoteFolder> for crate::api::oxicloud::RemoteFolder {
    fn into_into_dart(self) -> crate::api::oxicloud::RemoteFolder { self }
}

impl flutter_rust_bridge::IntoDart for crate::api::oxicloud::SyncConflict {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.item_path.into_into_dart().into_dart(),
            self.local_modified.into_into_dart().into_dart(),
            self.remote_modified.into_into_dart().into_dart(),
            self.local_size.into_into_dart().into_dart(),
            self.remote_size.into_into_dart().into_dart(),
            self.conflict_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::oxicloud::SyncConflict {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::oxicloud::SyncConflict> for crate::api::oxicloud::SyncConflict {
    fn into_into_dart(self) -> crate::api::oxicloud::SyncConflict { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::SyncItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.is_directory.into_into_dart().into_dart(),
            self.size.into_into_dart().into_dart(),
            self.content_hash.into_into_dart().into_dart(),
            self.local_modified.map(|v| v.timestamp_millis()).into_into_dart().into_dart(),
            self.remote_modified.map(|v| v.timestamp_millis()).into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.etag.into_into_dart().into_dart(),
            self.mime_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::SyncItem {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::SyncItem> for crate::domain::entities::SyncItem {
    fn into_into_dart(self) -> crate::domain::entities::SyncItem { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::SyncStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::domain::entities::SyncStatus::Synced => vec![0.into_dart()].into_dart(),
            crate::domain::entities::SyncStatus::Pending => vec![1.into_dart()].into_dart(),
            crate::domain::entities::SyncStatus::Syncing => vec![2.into_dart()].into_dart(),
            crate::domain::entities::SyncStatus::Conflict(field0) => {
                vec![3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::domain::entities::SyncStatus::Error(field0) => {
                vec![4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::domain::entities::SyncStatus::Ignored => vec![5.into_dart()].into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::SyncStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::SyncStatus> for crate::domain::entities::SyncStatus {
    fn into_into_dart(self) -> crate::domain::entities::SyncStatus { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::SyncDirection {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::domain::entities::SyncDirection::Upload => 0.into_dart(),
            crate::domain::entities::SyncDirection::Download => 1.into_dart(),
            crate::domain::entities::SyncDirection::None => 2.into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::SyncDirection {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::SyncDirection> for crate::domain::entities::SyncDirection {
    fn into_into_dart(self) -> crate::domain::entities::SyncDirection { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::ConflictType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::domain::entities::ConflictType::BothModified => 0.into_dart(),
            crate::domain::entities::ConflictType::DeletedLocally => 1.into_dart(),
            crate::domain::entities::ConflictType::DeletedRemotely => 2.into_dart(),
            crate::domain::entities::ConflictType::TypeMismatch => 3.into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::ConflictType {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::ConflictType> for crate::domain::entities::ConflictType {
    fn into_into_dart(self) -> crate::domain::entities::ConflictType { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::ConflictInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        vec![
            self.conflict_type.into_into_dart().into_dart(),
            self.detected_at.timestamp_millis().into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::ConflictInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::ConflictInfo> for crate::domain::entities::ConflictInfo {
    fn into_into_dart(self) -> crate::domain::entities::ConflictInfo { self }
}

impl flutter_rust_bridge::IntoDart for crate::domain::entities::ConflictResolution {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::domain::entities::ConflictResolution::KeepLocal => 0.into_dart(),
            crate::domain::entities::ConflictResolution::KeepRemote => 1.into_dart(),
            crate::domain::entities::ConflictResolution::KeepBoth => 2.into_dart(),
            crate::domain::entities::ConflictResolution::Skip => 3.into_dart(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::entities::ConflictResolution {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::entities::ConflictResolution> for crate::domain::entities::ConflictResolution {
    fn into_into_dart(self) -> crate::domain::entities::ConflictResolution { self }
}

// Section: CST allocation functions

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_cst_new_box_autoadd_Chrono_Utc(value: i64) -> *mut i64 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_cst_new_box_autoadd_i_64(value: i64) -> *mut i64 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_cst_new_box_autoadd_sync_config() -> *mut wire_cst_sync_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_sync_config {
        sync_folder: core::ptr::null_mut(),
        database_path: core::ptr::null_mut(),
        sync_interval_seconds: Default::default(),
        max_upload_speed_kbps: Default::default(),
        max_download_speed_kbps: Default::default(),
        delta_sync_enabled: Default::default(),
        delta_sync_min_size: Default::default(),
        pause_on_metered: Default::default(),
        wifi_only: Default::default(),
        watch_filesystem: Default::default(),
        ignore_patterns: core::ptr::null_mut(),
        notifications_enabled: Default::default(),
        launch_at_startup: Default::default(),
        minimize_to_tray: Default::default(),
    })
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_cst_new_list_String(len: i32) -> *mut wire_cst_list_String {
    let wrap = wire_cst_list_String {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(core::ptr::null_mut(), len),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_cst_new_list_prim_u_8_strict(len: i32) -> *mut wire_cst_list_prim_u_8_strict {
    let ans = wire_cst_list_prim_u_8_strict {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
}

// Section: FFI exports (matching Dart CST wire signatures)

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_config(port_: i64) {
    wire__crate__api__oxicloud__get_config_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_conflicts(port_: i64) {
    wire__crate__api__oxicloud__get_conflicts_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_pending_items(port_: i64) {
    wire__crate__api__oxicloud__get_pending_items_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_remote_folders(port_: i64) {
    wire__crate__api__oxicloud__get_remote_folders_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_server_info(port_: i64) {
    wire__crate__api__oxicloud__get_server_info_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_folders(port_: i64) {
    wire__crate__api__oxicloud__get_sync_folders_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_history(port_: i64, limit: u32) {
    wire__crate__api__oxicloud__get_sync_history_impl(port_, limit)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_status(port_: i64) {
    wire__crate__api__oxicloud__get_sync_status_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__simple__greet(
    name: *mut wire_cst_list_prim_u_8_strict,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    wire__crate__api__simple__greet_impl(name)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__simple__init_app(port_: i64) {
    wire__crate__api__simple__init_app_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__initialize(
    port_: i64, config: *mut wire_cst_sync_config,
) {
    wire__crate__api__oxicloud__initialize_impl(port_, config)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__is_logged_in(port_: i64) {
    wire__crate__api__oxicloud__is_logged_in_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__login(
    port_: i64,
    server_url: *mut wire_cst_list_prim_u_8_strict,
    username: *mut wire_cst_list_prim_u_8_strict,
    password: *mut wire_cst_list_prim_u_8_strict,
) {
    wire__crate__api__oxicloud__login_impl(port_, server_url, username, password)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__logout(port_: i64) {
    wire__crate__api__oxicloud__logout_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__resolve_conflict(
    port_: i64,
    conflict_id: *mut wire_cst_list_prim_u_8_strict,
    resolution: i32,
) {
    wire__crate__api__oxicloud__resolve_conflict_impl(port_, conflict_id, resolution)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__set_sync_folders(
    port_: i64, folder_ids: *mut wire_cst_list_String,
) {
    wire__crate__api__oxicloud__set_sync_folders_impl(port_, folder_ids)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__shutdown(port_: i64) {
    wire__crate__api__oxicloud__shutdown_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__start_sync(port_: i64) {
    wire__crate__api__oxicloud__start_sync_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__stop_sync(port_: i64) {
    wire__crate__api__oxicloud__stop_sync_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__sync_now(port_: i64) {
    wire__crate__api__oxicloud__sync_now_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_oxicloud_app_wire__crate__api__oxicloud__update_config(
    port_: i64, config: *mut wire_cst_sync_config,
) {
    wire__crate__api__oxicloud__update_config_impl(port_, config)
}

/// Dummy function to prevent tree-shaking of the native library.
#[no_mangle]
pub extern "C" fn dummy_method_to_enforce_bundling() -> i64 {
    0
}
